#!/bin/sh
cordova requirements
cordova build android
adb install -r -t 'platforms/android/app/build/outputs/apk/debug/app-debug.apk'
name=$(grep -oP '(?<=id=").*?(?=\" version)' config.xml)
adb shell am start "$name/.MainActivity"
